name: agrolink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your original Firebase packages
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3

  provider: ^6.1.5+1
  razorpay_flutter: ^1.4.0

  http: ^1.2.1
  dio: ^4.0.6
  url_launcher: ^6.3.2

  image_picker: ^1.2.0
  imagekit_io: ^0.0.3

  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.2.3 # <-- ADDED THIS LINE (Using latest stable version)
  geolocator: ^12.0.0

  fl_chart: ^1.1.1
  curved_navigation_bar: ^1.0.6
  glassmorphism_ui: ^0.3.0
  animated_background: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/category_mappings.json
    - assets/data/rainfall_frontend_mappings.json
    - .env
    - assets/comparison_prices.json
    - assets/agrolink_logo.png
    - assets/crop_plans.json
    - assets/wheat.jpg
    - assets/doodles.png
    - assets/doodles2.png
    - assets/doodles3.png
    - assets/farm.jpg


# This section fixes all the errors
dependency_overrides:
  fluttertoast: 8.2.14  # Fixes the 'Registrar' build error
  web: 1.0.0       # Fixes the dependency deadlock